name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - LICENSE


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            /*/*.zip
          tag_name: AutoRelease
          token:  ${{ secrets.TEST_TOKEN }}
        env:
          GITHUB_REPOSITORY: VaLueS6655/Genshin_Impact_Teleport_Files
