name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - LICENSE


jobs:
  build:
    runs-on:  windows-2019

    steps:
      - name: git allow longname
        run: git config --global core.longpaths true
      - name: checkout
        uses: actions/checkout@v3
      - name: python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.10.9
      - name: build
        uses: TheDoctor0/zip-release@0.7.0
        with: 
          type: 'zip'
          filename: '${{ build.path }}.zip'
          exclusions: '*.git* AutoGeneratePoint'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.zip
            */*.zip
            */*/*.zip
            */*/*/*.zip
            */*/*/*/*.zip
            */*/*/*/*/*.zip
          tag_name: AutoRelease
          token:  ${{ secrets.TEST_TOKEN }}
        env:
          GITHUB_REPOSITORY: VaLueS6655/Genshin_Impact_Teleport_Files
